---
# We just wrap `build` so this is really it
name: "jellyfin-ffmpeg"
version: "7.1.1-7"
packages:
  - bullseye-amd64
  - bullseye-arm64
  - bookworm-amd64
  - bookworm-arm64
  - trixie-amd64
  - trixie-arm64
  - jammy-amd64
  - jammy-arm64
  - noble-amd64
  - noble-arm64
